---
apiVersion: v1
kind: Namespace
metadata:
  name: python-dogstatsd-demo
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-dogstatsd-demo
  namespace: python-dogstatsd-demo
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-dogstatsd-demo
  metrics:
  - type: External
    external:
      target:
        type: AverageValue
        averageValue: 10
      metric:
        name: python_dogstatsd_demo.requests.increment
        selector:
          matchLabels:
            kube_namespace: python-dogstatsd-demo
            kube_deployment: python-dogstatsd-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-dogstatsd-demo
  name: python-dogstatsd-demo
  namespace: python-dogstatsd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-dogstatsd-demo
  template:
    metadata:
      labels:
        app: python-dogstatsd-demo
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
      - image: iulian77/python-dogstatsd-demo:latest
        name: app
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-dogstatsd-demo
  name: python-dogstatsd-demo
  namespace: python-dogstatsd-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: python-dogstatsd-demo
  type: ClusterIP

